version: "3"
services:
  saving-goals-api:
    build:
      context: .
      dockerfile: ./resources/docker/Dockerfile.api
    ports:
      - "8088:8088"
    restart: on-failure
    depends_on:
      - saving-goals-postgres
    environment:
      DATABASE_HOST: saving-goals-postgres

  saving-goals-consumers:
    build:
      context: .
      dockerfile: ./resources/docker/Dockerfile.consumers
    restart: on-failure
    command: ["saving-goals-consumers"]
    depends_on:
      - saving-goals-postgres
    environment:
      KAFKA_HOST: kafka
      DATABASE_HOST: saving-goals-postgres

  saving-goals-postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: on-failure
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: saving_goals
      POSTGRES_USER: saving_goals_api
      POSTGRES_PASSWORD: saving_goals_api

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
